// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using yapa_api.Models;

namespace yapaapi.Migrations
{
    [DbContext(typeof(personalDbContext))]
    [Migration("20190128062209_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("yapa_api.Models.Expense", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnName("createdon");

                    b.Property<string>("Description")
                        .HasColumnName("description");

                    b.Property<Guid>("ExpenseId")
                        .HasColumnName("expenseid");

                    b.Property<string>("ExpenseType")
                        .IsRequired()
                        .HasColumnName("expensetype");

                    b.Property<long>("MainCategoryId")
                        .HasColumnName("maincategoryid");

                    b.Property<double>("Price")
                        .HasColumnName("price");

                    b.Property<string>("SpentAt")
                        .HasColumnName("spentat");

                    b.Property<long>("SubCategoryId")
                        .HasColumnName("subcategoryid");

                    b.Property<DateTime>("Time")
                        .HasColumnName("time");

                    b.HasKey("Id");

                    b.HasIndex("MainCategoryId");

                    b.HasIndex("SubCategoryId");

                    b.ToTable("expenses");
                });

            modelBuilder.Entity("yapa_api.Models.MainCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnName("description")
                        .HasMaxLength(4000);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasMaxLength(400);

                    b.HasKey("Id");

                    b.ToTable("expense_main_category");
                });

            modelBuilder.Entity("yapa_api.Models.SubCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnName("description");

                    b.Property<long>("MainCategoryId")
                        .HasColumnName("maincategoryid");

                    b.Property<string>("Name")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("MainCategoryId");

                    b.ToTable("expense_sub_category");
                });

            modelBuilder.Entity("yapa_api.Models.Expense", b =>
                {
                    b.HasOne("yapa_api.Models.MainCategory", "MainCategory")
                        .WithMany("Expenses")
                        .HasForeignKey("MainCategoryId")
                        .HasConstraintName("FK_expenses_main_category_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("yapa_api.Models.SubCategory", "SubCategory")
                        .WithMany("Expenses")
                        .HasForeignKey("SubCategoryId")
                        .HasConstraintName("FK_expenses_sub_category_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("yapa_api.Models.SubCategory", b =>
                {
                    b.HasOne("yapa_api.Models.MainCategory", "MainCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("MainCategoryId")
                        .HasConstraintName("FK_sub_category_main_category_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
